[project]
name = "2026-codyssey-advance"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "imbalanced-learn>=0.14.2",
    "ipykernel>=7.4.0",
    "jupyterlab>=4.6.4",
    "konlpy>=0.6.0",
    "matplotlib>=3.11.2",
    "nltk>=3.10.3",
    "numpy>=2.5.3",
    "opencv-python>=5.0.0.93",
    "pandas>=3.0.6",
    "pytest>=9.1.1",
    "ruff>=0.16.10",
    "scikit-learn>=1.9.1",
    "scipy>=1.18.1",
    "seaborn>=0.13.2",
    "shap>=0.52.0",
    "xgboost>=3.4.1",
    "yfinance>=1.7.0",
]
